services:

  #################################
  # Reverse Proxy (Nginx)
  # Steuert den Zugriff auf /evaschiffmann, /matomo, /grafana
  #################################
  reverse_proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/config/reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  
      - matomo:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - portal
      - grafana
      - matomo
    networks:
      - matomo_network

  matomo_web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html
      - ./nginx/config/matomo.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - matomo
    networks:
      - matomo_network


  #################################
  # MariaDB Service
  #################################
  db:
    image: mariadb:10.6
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env
    networks:
      - matomo_network

  #################################
  # Matomo Instance
  #################################
  matomo:
    image: matomo:5.2.2-fpm-alpine
    restart: always
    depends_on:
      - db
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    expose:
      - "9000"
    env_file:
      - ./db.env
    networks:
      - matomo_network

  #################################
  # Grafana Instance
  #################################
  grafana:
    image: grafana/grafana-oss
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,yesoreyeram-infinity-datasource,marcusolsson-gantt-panel
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=true
      - GF_SERVER_ROUTER_LOGGING=true
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_PORT=3000
    env_file:
      - ./grafana.env
    networks:
      - matomo_network


  #################################
  # Webserver für evaschiffmann.de
  #################################
  portal:
    image: nginx:alpine
    restart: always
    volumes:
    - ./portal/evaschiffmann:/usr/share/nginx/html:ro  
    networks:
      - matomo_network

#################################
# Netzwerke & Volumes
#################################
volumes:
  db:
  matomo:
  grafana-storage:

networks:
  matomo_network:
    driver: bridge
