services:
  db:
    image: mariadb:10.6
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env
    networks:
      - matomo_network

  matomo:
    image: matomo:5.0.2-fpm-alpine
    restart: always
    depends_on:
      - db
    links:
      - db
    volumes:
      - matomo:/var/www/html # matomo saved on a volume
      - ./config.ini.php:/var/www/html/config/config.ini.php # matomo config saved on device
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env
    networks:
      - matomo_network

  web:
    image: nginx:alpine
    restart: always
    depends_on:
      - matomo
    volumes:
      - matomo:/var/www/html:ro
      - ./nginx/config/matomo.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Mount SSL-Zertifikate in den Container
    ports:
      - 8111:443  # Matomo über HTTPS erreichbar
    networks:
      - matomo_network

  portal:
    image: nginx:alpine
    restart: always
    volumes:
      - ./portal:/usr/share/nginx/html:ro
      - ./nginx/config/portal.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Mount SSL-Zertifikate in den Container
    networks:
      - matomo_network
    depends_on:
      - web
    ports:
      - 8080:443

volumes:
  db:
  matomo:

networks:
  matomo_network:
    driver: bridge
