services:

#################################
# MariaDB Service
#################################
  db:
    image: mariadb:10.6
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env
    networks:
      - matomo_network

#################################
# Matomo Service
# API-Token: ec1e6b6dafaf9db920992d4241b6df53
#################################

  matomo:
    image: matomo:5.0.2-fpm-alpine
    restart: always
    depends_on: # only start if db is up and running
      - db
    volumes:
      - matomo:/var/www/html # matomo saved on a volume
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env
    networks:
      - matomo_network

#################################
# nginx reverse-proxy to matomo 
# https://localhost:8111
#################################

  web:
    image: nginx:alpine
    restart: always
    depends_on: # only start if matomo is up and running
      - matomo
    volumes:
      - matomo:/var/www/html:ro
      - ./nginx/config/matomo.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  
    ports:
      - 8111:443  # matomo via https
    networks:
      - matomo_network

#################################
# Webserver evaschiffmann.de
# https://localhost:8080
#################################

  portal:
    image: nginx:alpine
    restart: always
    volumes:
      - ./portal:/usr/share/nginx/html:ro
      - ./nginx/config/portal.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  
    networks:
      - matomo_network
    depends_on: # only start if tracking is available (matomo started and can be contacted)
      - web
    ports:
      - 8080:443 # evaschiffmann via https

#################################
# Grafana
# https://localhost:8080
#################################

  grafana:
    image: grafana/grafana-oss
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./nginx/ssl:/etc/nginx/ssl:ro
    environment: # persistently modify configurations
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,yesoreyeram-infinity-datasource # to be added.. always to latest version is used
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/nginx/ssl/localhost.crt
      - GF_SERVER_CERT_KEY=/etc/nginx/ssl/localhost.key
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=true # because signature problems with different versions of the project 
    env_file:
      - ./grafana.env
    networks:
      - matomo_network
    depends_on:
      - db
    ports:
      - 3000:3000 # Grafana via HTTPS

volumes:
  db:
  matomo:
  grafana-storage:

networks:
  matomo_network:
    driver: bridge